# Generated by Django 4.1.7 on 2023-03-14 15:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='TradeFair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='title name', max_length=255)),
                ('description', models.TextField(default='delicious')),
                ('image1', models.ImageField(blank=True, null=True, upload_to='images/large')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='images/small')),
                ('category', models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='myapp.category')),
                ('language', models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='myapp.language')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
