# Generated by Django 4.1.7 on 2023-03-14 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messebranchen', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='language',
            old_name='name',
            new_name='language_name',
        ),
    ]
