# Generated by Django 4.1.3 on 2023-03-08 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('airport', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='messezentren',
        ),
    ]
