# Generated by Django 4.1.7 on 2023-02-21 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeview', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('avatar', models.ImageField(upload_to='uploads/')),
            ],
        ),
        migrations.DeleteModel(
            name='Image',
        ),
    ]
