# Generated by Django 4.1.7 on 2023-02-21 00:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homeview', '0002_student_delete_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='avatar',
            new_name='path',
        ),
    ]
