# Generated by Django 4.1.3 on 2023-03-08 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='messezentren',
            fields=[
                ('zentren_id', models.IntegerField(primary_key=True, serialize=False)),
                ('firma', models.CharField(max_length=30)),
                ('firma_en', models.CharField(max_length=30)),
                ('firma_fr', models.CharField(max_length=30)),
                ('firma_es', models.CharField(max_length=30)),
                ('firma_ru', models.CharField(max_length=30)),
                ('firma_cn', models.CharField(max_length=30)),
                ('strasse', models.CharField(max_length=30)),
                ('text_de', models.TextField()),
                ('text_en', models.TextField()),
                ('text_fr', models.TextField()),
                ('text_es', models.TextField()),
                ('text_ru', models.TextField()),
                ('text_cn', models.TextField()),
                ('ort', models.IntegerField()),
                ('plz', models.CharField(max_length=30)),
                ('fax', models.CharField(max_length=30)),
                ('url', models.CharField(max_length=30)),
                ('tel', models.CharField(max_length=30)),
                ('lat', models.CharField(max_length=11)),
                ('lon', models.CharField(max_length=11)),
                ('land_id', models.IntegerField()),
                ('email', models.CharField(max_length=30)),
                ('angelegt', models.DateField()),
            ],
            options={
                'db_table': 'messezentren',
            },
        ),
    ]
