# Generated by Django 4.1.6 on 2023-03-24 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "messezentren",
            "0002_alter_messezentren_options_messezentren_anfahrt_cn_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="messezentren",
            name="hallenanzahl",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
